Repository BenDMyers/showmy.chat, pull requests merged in 2022-05, with the labels that each got.

#143 show and update url on form input
  package-lock.json
  src/index.html
Labels: URL builder

#145 Enable users to disable animated emotes in their overlays
  netlify/functions/serverless/cleanse-query-parameters.js
  src/_data/defaults.js
  src/docs/configuration.html
  src/index.html
  src/scripts/handleChat.mjs
Labels: overlay configuration

#147 Clean up lint warnings
  .eslintrc.json
  netlify/functions/serverless/cleanse-query-parameters.js
  netlify/functions/serverless/index.js
  package-lock.json
  package.json
  src/scripts/bttvIntegration.mjs
  src/scripts/color.mjs
  src/scripts/demo.mjs
  src/scripts/handleChat.mjs
Labels: low priority
